### ISSUE TITLE
Support for scalr::abs() similar to std::chrono::abs()

### ISSUE THREAD

**Issue by dpurgin** [doganulus/scalr#4]
Hey, 

thanks again for the great library. 

In a project I require an absolute value of a length like this: 

```
// this is a pseudocode
function needsCorrection(scalr::millimeters difference) {
    return abs(difference) <= 3_mm;
}
```

There is a workaround using `scalr::millimeters{std::abs(difference.value())} <= 3_mm` but it's not pretty. C++17 has a `std::chrono::abs(std::chrono::duration)` for that, but it can't be mapped to a `scalr::abs()` since it conflicts with a helper struct `scalr::abs<>` from `unit.hpp`. So I ended up implementing a `scalr::qabs()` in `quantity.hpp`: 
 
```c++
template<typename Rep, typename Unit>
constexpr auto qabs(quantity<Rep, Unit> value)
{
  return value > value.zero()? value: -value;
}
```

From what I understand, the existing `struct scalr::abs<>` is an implementation detail. Could it be moved to the namespace `detail`, so that we could have `scalr::abs()` consistent with `std::chrono::abs`?

Cheers

**Comment by doganulus** [comment]
You are right here. The library should be consistent with `std::chrono` in this regard. So it seems the best solution to move the helper struct under `detail` namesapce.
