### ISSUE TITLE
Non-explicit quantity::operator bool() 

### ISSUE THREAD

**Issue by dpurgin** [doganulus/scalr#7]
Hello, 

I've stumbled upon an issue involving implicit bool conversion when using scalr.

In the following snippet the result of the call is kind of unexpected: 

```c++
void fn(int arg) {
  // ...
}

fn(scalr::millimeters{10});
```

Due to non-explicit `quantity::operator bool()`, the value `scalr::millimeters{10}` is converted to `true` which is then implicitly converts to `1`. Either declaring the operator bool `explicit` or removing it completely causes a compile error with a data type mismatch, as expected (I've declared the operator `explicit` in the project where I use scalr). 

Is there a particular reason for the non-explicit `operator bool`? I've looked into C++14 standard and libstdc++ implementation and it seems there is no such operator in `std::chrono::duration`. Should it be removed for consistency with the chrono library?

**Comment by doganulus** [comment]
The operator `bool` could be removed for the sake of compatibility and preventing such surprises.

**Comment by doganulus** [comment]
Closed by #8.
